console.log('listOfPhrase');
listOfPhrase=([
   {
      "Start Game":"شروع بازی",
      "Home":"خانه",
      "Play online with your friends":"با دوستات آنلاین بازی کن ",
      "Play with your friends":"با دوستات بازی کن",
      "Free to Play":"بازی رایگان",
      "No Download Required":"بدون نیاز به دانلود ",
      "Just sign up and play!":"برای بازی فقط ثبت نام کنید.",
      "PLAY NOW":"حالا بازی کن",
      "Guest User":"کاربر مهمان",
      "Play":"بازی",
      "Setting":"تنظیمات",
      "Earn Coin":"سکه",
      "Share":"اشتراک‌گذاری",
      "About":"درباره ما",
      "Contact Us":"تماس با ما",
      "Events":"رویداد",
      "Help & Learn Play":"آموزش بازی",
      "Profile Information":"اطلاعات کاربری",
      "name":"نام",
      "Name":"نام",
      "PROFILE PHOTO":"عکس نمایه",
      "Upload Photo":"بارگذاری عکس",
      "Setting":"تنظیمات",
      "Sound":"صدا",
      "Language":"زبان",
      "UPDATE":"به روز رسانی",
      "Choose Hokm:":":انتخاب حکم",
      "Hokm":"حکم",
      "Share the app if you like":"اشتراک گذاری",
      "Telegram":"تلگرام",
      "Whatsapp":"واتساپ",
      "Facebook":"فیسبوک",
      "Twitter":"توییتر",
      "Email":"ایمیل",
      "Log in": "ورود",
      "Log out": "خروج",
      "Guest user":"کاربر مهمان",
      "Let's play Hukm 😍":"رفیق بیا حکم بازی کنیم 😍",
      "Tap here to share the app on Telegram.":"برای اشتراک گذاری از طریق تلگرام اینجا را ضربه بزنید.",
      "Tap here to share the app on Whatsapp.":"برای اشتراک گذاری از طریق واتساپ اینجا را ضربه بزنید.",
      "Tap here to share the app on Facebook.":"برای اشتراک گذاری از طریق فیسبوک اینجا را ضربه بزنید.",
      "Tap here to share the app on Twitter.":"برای اشتراک گذاری از طریق توییتر اینجا را ضربه بزنید.",
      "Tap here to share the app on Email.":"برای اشتراک گذاری از طریق ایمیل اینجا را ضربه بزنید.",
      "Choose Hokm":"انتخاب حکم",
      "Points":"امتیاز",
      "Hands":"دست", 
      "Well done, you win the Hand":"عالی بود دست بردی",
      "You loose the hand":"دست باختی",
      "Update Done.":"بروز رسانی انجام شد",
      "Name must be more than 5 characters and less than 12 characters!":"اسم انتخابی باید بیشتر از شش حرف باشد",
      "The king is player":"حاکم٬ بازیکن شماره",
      "Disconnected":"اینترنت وصل نیست",
      "Vibration":"لرزش",
      "You Win!":"شما بردی",
      "You Loose!":"شما باختی",
      "You played awesome.":"عالی بازی کردی",
      "Try to win.":"سعی کن ببری",
      "Fast Game":"بازی سریع",
      "Slow Game":"بازی آرام",
      "Vibration ON":"لرزش روشن",
      "Vibration OFF":"لرزش خاموش",
      "Sound OFF":"صدا خاموش",
      "Sound ON":"صدا روشن",
      "Edit Profile":"ویرایش  نمایه",
      "Please Uplaod your image":"لطفا عکس خود را بروز کنید.",
      "king is player No":"حاکم بازیکن شماره است.",
      "The game has just begun":"بازی شروع شد.",
      "ALL player ready":"همه بازیکنان آماده هستند.",
      "Free Seat":"جای خالی",
      "Stand Up":"برخواستن",
      "Yes":"بله",
      "invite":"دعوت",
      "Eject":"اخراج",
      "You don't have enough Coin":"شما سکه کافی ندارید.",
      "You need":"شما نیاز به",
	  // به خط زیر ربط دارد جمله به این شکل هست :‌ You need 10 Coins for play in this room
      "Coins for play in this room":"سکه برای بازی در این اتاق دارید",
      "Room manger kicked the player on seat No.":"مدیر اتاق اخراج کرد بایکن شماره",
      "Send To":"فرستاد به",  
      "Available Rooms":"نمایش اتاق عمومی",
      "Room Name":"نام اتاق",
      "Create A Room": "ایجاد اتاق بازی",
      "e.g. kings of hokm": "نمونه: سلاطین حکم",
      "Public Room not Found": "اتاق عمومی یافت نشد",
      "Create your own": "اتاق مخصوص خود را بساز",
      "private room": "اتاق خصوصی",
      "Top Player": "بازیکنان برتر",
      "Coin":"سکه",
      "Continue":"ادامه",
      "Error, you can't play multi game at the same time":"خطا، شما نمی توانید در چند اتاق بازی کنید.",
      "You are Fired by ??! Because you are very slow":"شما به دلیل سرعت کم در بازی اخراج شدید.",
      "You are Fired by ??! Because you cheated":"شما به دلیل تقلب از اتاق اخراج شدید.",
      "Gift not sent!":"هدیه فرستاده نشد!",
      "Room Closed":"اتاق بسته شد",
      "You kick out by room manger":"مدیر اتاق شما را اخراج کرد.",
      "Find Joker and Receive400 coins??":"کارت جوکر را پیدا کنید و 400 سکه بدست آورید.??",
      "You didn't find Joker But you Receive40??":"کارت جوکر را پیدا نکردی اما 40 سکه هدیه گرفتی",
      "Cheat investigation is happened and new hand start.":"درخواست جستجو در مورد تفلب صورت گرفت و دست جدید شروع شد.",
      "You need Coins for play in this room":"شما به سکه بیشتری برای بازی در این اتاق نیاز دارید.",
      "Room manger kicked the player on seat No.":"مدیر اتاق بازیکن ",
      "Public Room not Found":"اتاق عمومی یافت نشد",
      "Sent.":"فرستاده شد.",
      "Friend Request sent.":"درخواست دوستی ارسال شد.",
      "Please Login":"لطفا وارد شوید.",
      "Find Joker card and Win":"کارت جوکر را پیدا کن و ببر",
      "Pay 10, win 30":"ده سکه بده و سی سکه ببر",
      "Daily Free Coin":"سکه رایگان روزانه",
      "Find Joker card and Win 400 Coins":"کارت جوکر را پیدا کن و 400 سکه ببر",
      "Who is cheater ?":"متقلب کیست؟",
      "Details: your partner guess this user cheats and if you believe cheating is happened tap 'Accept' or not, 'Reject'. consider that if the guess is wrong, you will loose the hand and if you are right, you will Win.":"یار شما حدس می زند که تقلب صورت گرفته، اگر شما با یارتان موافقید روی قبول  و اگر مخالفی روی رد ضربه بزنید. در نظر داشته باشید،اگر حدستان اشتباه باشد یک امتیاز از دست می دهید و اگر حدستان درست باشد یک امتیاز بدست می آورید.",
      "Close":"بستن",
      "Your partner tells you the other user is cheats, do you agree?":"یارت میگه که حریف تقلب کرد. درسته؟",      
      "Reject":"رد", 
      "Create":"بساز",
      "Win Coins":"3 کارت",
      "Login Error":"خطای ورود",
      "Please enter Room Name more than 6 character!":"لطفا نام با حداقل 6 کارکتر بسازید.",
      "Please enter minimum 30 coin":" لطفا حداقل 30 سکه بزارید",
      "Invite":"دعوت",
      "UpDate not done":"آپدیت تکمیل نشد.",
      "Server Error, Create file Problem":"خطای سرور، خطا در ایجاد فایل",
      "Top Ten":"10بازیکن برتر",
      "Please Wait for Ads to Auto play...":"لطفا صبر کنید تا ویدیو تبلیغاتی نمایش داده شود...",
      "Congratulations, You Earned 17 Coins.":"تبریک. 17 سکه بدست آوردی",
      "Something is wrong, Please try again after 5 minutes.":"خطا رخ داد،لطفابعد از پنج دقیقه دوباره تلاش کنید.",
      "Your Coins":"سکه های شما",
      "Tap here to Earn 17":"اینجا را ضربه بزنید برای دریافت 17",
      "Coins":"سکه",
      "7 hands":"هفت دست",
      "5 hands":"پنج دست",
      "3 hands":"سه دست",
      "You Win 30 coins":"سی سکه بردی",
      "You Lose 10 coin":"ده سکه باختی",
      "Ready":"آماده‌ام‎",
	   "Experience":"تجربه",
	   "Game created":"بازی ایجاد شد",
	   "Room created":"اتاق ایجاد شد",
	   "Cool, You are creator of this game":"عالی، شما اتاق را ساختید",
	   "Leave":"ترک اتاق",
      "Are you sure?":"مطمئنی؟",
      "Accept":"قبول",
      "Jokeret gives  5$ Gift Card to top 10 players Every two weeks. The End of First Round is 29 March 2020.":"جوکرت کارت هدیه 500.000ریال دیجی‌کالا را هر 2‌هفته به 10‌بازیکن برتر هدیه می‌دهد. پایان اولین دور،10فروردین 99",
      "Jokeret gives  5$ Gift Card to top 10 players. The End of Second Round is 18 April 2020.":"جوکرت کارت هدیه 500.000ریال دیجی‌کالا را به 10‌بازیکن برتر هدیه می‌دهد. پایان دومین دور،30فروردین 99",
      "Winners of first round(Tep here)":"برندگان دور اول (اینجا ضربه بنزید)",
      "No.":"شماره",
      "Kick the user":'اخراج کاربر از جایگاه',
      "Gifts received":"هدایا دریافتی",
      "Gifts sent":"هدایا ارسالی",
      "Win":"برد",
      "Left":"ترک",
      "Gifts":"هدایا",
      "Standard":"معمولی",
      "Game":"بازی",
      "Invite your friends.":"دوستاتُ دعوت کن",
      "Hello":"سلام",
      "Please play faster":"لطفا سریع بازی کن",
      "Good Game":"عالی بازی کردی",
      "Details: your partner must confirm cheat is happen and if you are wrong, your team loose this hand. and if you are right, your team wins this hand.":"یارت باید تایید کنه که تقلب شده و اگراشتباه کرده باشی، تیم شما بازنده این دست خواهد بود و اگر درست گفته باشی که حریف تقلب کرده. تیم شما این دست را می برد.",
      "Tap here to invite your friends from Telegram.":"برای دعوت دوستت از طریق تلگرام اینجا را ضربه بزن",
      "Tap here to invite your friends from WhatsApp.":"برای دعوت دوستت از طریق واتساپ اینجا را ضربه بزن",
      "Tap here to invite your friends from Facebook.":"برای دعوت دوستت از طریق فیسبوک اینجا را ضربه بزن",
      "Tap here to invite your friends from twitter.":"برای دعوت دوستت از طریق توییتر اینجا را ضربه بزن",
      "Tab here to invite your friends from email.":"برای دعوت دوستت از طریق ایمیل اینجا را ضربه بزن",
      "Top players with more coins will earn Gift Cards tap here.":"به بازیکنان دارای بیشترین سکه، کارت هدیه داده می شود.(ضربه بزنید)‎",
      "To learn how to play tap here.":"برای دیدن آموزش بازی اینجا را ضربه بزنید.",
      "To be familiar with how to earn coin tap here.":"برای آشنایی با روش های بدست آوردن سکه اینجا را ضربه بزنید.",
      "Welcome, You receive 1000":"خوش آمدی، شما گرفتی 1000",
      "Image Profile": "تصویر نمایه",
      "Save":"دخیره",
      "You don't have enough Coin for playing in this room, Tap here to earn Coin.":"سکه کافی برای بازی در این اتاق را ندارید، برای بدست آوردن سکه ضربه بزنید.",
      "Required Coin for this room":"سکه مورد نیاز این اتاق",
      "You need to change name before Play Game":"برای بازی باید نام خود را بروز کنید",
      "Put more than 6 characters in your name.":"اسم باید بیشتر از 6 حرف باشد",
      "'Name must be more than 6 characters and less than 12 characters":"اسم انتخابی باید بیشتر از 6 حرف و کمتر از 12 حرف باشد",
      "Disconnected,Your Connection is poor":"ارتباط قطع شد. اینترنت شما ضعیف است",
      "4 Player": " چهار نفره",
      "2 Player": "دو نفره",
      "Single Player":"بازی تکی",
      "Player": "نفر",
      "Waiting":'صبر کنید',
      "Exit":"خروج",
      "Offline":"آفلاین",
      "Top Ten Winners of Gift Card of First Round (29/3/2020)":" ده بازیکن برنده کارت هدیه دور اول (10-01-99)",
      "LogIn/Register":"ورود/ثبت‌نام",
      "Tap here to going to previous section":"برای برگشت به قسمت قبل اینجا را ضربه بزنید",
      " If you are disconnected, Please refresh page":"در صورت قطعی اینترنت برای بازگشت به اتاق بازی  صفحه را رفرش کنید",
      " Cool,You are creator of this game 👍 ": " شما سازنده و مدیر اتاق هستید👏 ",
      "Muted":"قطع صدا",
      "UnMuted":"وصل صدا",
      "Room not found":"اتاق پیدا نشد",
      "Please Try Again":"مجدد تلاش کنید"
   },
   {
      "Home":"الرئيسية",
      "Play online with your friends (coming soon)":"العب على الانترنت مع أصدقائك",
      "Play with your friends":"اللعب مع أصدقائك",
      "Free to Play":"لعب مجاني",
      "Games and tournaments run 24/7":"الألعاب والبطولات تعمل 24/7",
      "No Download Required":"لا يوجد تحميل مطلوب",
      "Just sign up and play!":"مجرد تسجيل واللعب!",
      "PLAY NOW":"العب الان",
      "Guest User":"حساب زائر",
      "Play":"العب",
      "Setting":"ضبط",
      "Earn Coin":"كسب عملة",
      "Share":"شارك",
      "About":"عن جو كرت",
      "Contact Us":"اتصل بنا",
      "Events":"أحداث",
      "Help & Learn Play":"تعلم العب",
      "Profile Information":"وضع الملف الشخصي",
      "name":"اسم مستخدم",
      "PROFILE PHOTO":"صورة الملف الشخصي",
      "Upload Photo":"قم بتنزيل صورتك هنا",
      "Settings":"ضبط",
      "Sound":"صوت",
      "Language":"اللغة",
      "UPDATE":"حفظ",
      "Choose Hokm:":"اختيار حکم",
      "Hokm":"حکم",
      "Share the app if you like":"مشاركة التطبيق إذا أردت",
      "Telegram":" تلغرام",
      "Tap here to share the app on Telegram.":" انقر هنا لمشاركة التطبيق على  تلغرام.",
      "Whatsapp":"واتساب",
      "Tap here to share the app on Whatsapp.":" انقر هنا لمشاركة التطبيق على  واتساب.",
      "Facebook":"فیسبوغ",
      "Tap here to share the app on Facebook.":" انقر هنا لمشاركة التطبيق على  فیسبوغ.",
      "Twitter":"تویتر",
      "Tap here to share the app on Twitter.":" انقر هنا لمشاركة التطبيق على  تویتر.",
      "Email":"البريد الإلكتروني",
      "Tap here to share the app on Email.":" انقر هنا لمشاركة التطبيق على  البريد الإلكتروني.",
      "Log in": "سجِّل الدخول",
      "Guest user":"حساب زائر",
      "Let's play Hukm 😍":"Let's play Hokm 😍😎",
      "Choose Hokm":"اختيار حکم",
      "Points":"درجة",
      "Hands":"جلس",
      "Well done, you win the Hand":"Well done, you win the Hand",
      "Please Uplaod your image":"Please Uplaod your image",
      "king is player No":"king is player No",
      "The game has just begun":"The game has just begun",
      "ALL player ready":"ALL player ready",
      "Free Seat":"Free Seat",
      "Stand Up":"Stand Up",
      "Yes":"Yes",
      "Eject":"Eject",
      "You don't have enough Coin":"You don't have enough Coin",
      "You need":"You need", // به خط زیر ربط دارد جمله به این شکل هست :‌ You need 10 Coins for play in this room
      "Coins for play in this room":"Coins for play in this room",
      "Room manger kicked the player on seat No.":"Room manger kicked the player on seat No.",
      "Send To":"Send To", //فرستاد به
      "Available Rooms":"Available Rooms",
      "Room Name":"Room Name",
      "Create A Room": "Create A Room",
      "e.g. kings of hokm": "e.g. kings of hokm",
      "Public Room not Found": "Public Room not Found",
      "Create your own": "Create your own",
      "private room": "private room",
      "Top Player": "Top Player",
      "Coin":"Coin",
      "Continue":"Continue",
      "Error, you can't play multi game at the same time":"Error, you can't play multi game at the same time",
      "You loose the hand":"You loose the hand",
      "Update Done.":"Update Done.",
      "Name must be more than 5 characters and less than 12 characters!": "Name must be more than 5 characters and less than 12 characters!",
      "The king is player": "The king is player",
      "Disconnected": "Disconnected",
      "Vibration":"Vibration",
      "You Win!":"You Win!",
      "You Loose!":"You Loose!",
      "You played awesome.":"You played awesome.",
      "Try to win.": "Try to win.",
      "Fast Game":"Fast Game",
      "Slow Game": "Slow Game",
      "Vibration ON":"Vibration ON",
      "Vibration OFF": "Vibration OFF",
      "Sound OFF":"Sound OFF",
      "Sound ON": "Sound ON",
      "Edit Profile":"تعديل الملف الشخصي",
      "Log out": "تسجيل خروج",
      "You are Fired by ??! Because you are very slow":"You are Fired by ??! Because you are very slow",
      "You are Fired by ??! Because you cheated":"You are Fired by ??! Because you cheated",
      "Gift not sent!":"Gift not sent!",
      "Room Closed":"Room Closed",
      "You kick out by room manger":"You kick out by room manger",
      "Find Joker and Receive400 coins??":"Find Joker and Receive400 coins??",
      "You didn't find Joker But you Receive40??":"You didn't find Joker But you Receive40",
      "Cheat investigation is happened and new hand start.":"Cheat investigation is happened and new hand start.",
      "You need Coins for play in this room":"You need Coins for play in this room",
      "Room manger kicked the player on seat No.":"Room manger kicked the player on seat No.",
      "Public Room not Found":"Public Room not Found",
      "Create your own":"Create your own",
      "Sent.":"Sent.",
      "Friend Request sent.":"Friend Request sent.",
      "Please Login":"Please Login",
      "Find Joker card and Win":"Find Joker card and Win",
      "Pay 10, win 30":"Pay 10, win 30",
      "Daily Free Coin":"Daily Free Coin",
      "Find Joker card and Win 400 Coins":"Find Joker card and Win 400 Coins",
      "Who is cheater ?":"Who is cheater ?",
      "Close":"Close",
      "Your partner tells you the other user is cheats, do you agree?":"Your partner tells you the other user is cheats, do you agree?",
      "Details: your partner guess this user cheats and if you believe cheating is happened tap 'Accept' or not, 'Reject'. consider that if the guess is wrong, you will loose the hand and if you are right, you will Win.":"",      
      "Accept":"Accept",
      "Reject":"Reject",
      "Create":"Create",
      "Win Coins":"Win Coins",
      "Login Error":"Login Error",
      "Please enter room Name more than 6 character!":"Please enter room Name more than 6 character!",
      "Please enter minimum 30 coin":"Please enter minimum 30 coin",
      "Free Seat":"Free Seat",
      "Invite":"Invite",
      "UpDate not done":"UpDate not done",
      "Server Error, Create file Problem":"Server Error, Create file Problem",
      "Top Ten":"Top Ten",
	   "Please Wait for Ads to Auto play...":"Please Wait for Ads to Auto play...",
      "Congratulations, You Earned 17 Coins.":"Congratulations, You Earned 17 Coins.",
      "Something is wrong, Please try again after 5 minutes.":"Something is wrong, Please try again after 5 minutes.",
      "Your Coins":"Your Coins",
      "Tap here to Earn 17":"Tap here to Earn 17",
      "Coins":"Coins",
      "7 hands":"7دست",
      "5 hands":"5دست",
      "3 hands":"3دست",
      "You Win 30 coins":"You Win 30 coins",
      "You Lose 10 coin":"You Lose 10 coin",
      "Ready":"Ready",
	   "Experience":"Experience",
	   "Game created":"Game created",
	   "Room created":"Room created",
	   "Cool, You are creator of this game":"Cool, You are creator of this game",
	   "Leave":"Leave",
      "Are you sure?":"Are you sure?",
      "Accept":"Accept",
      "Jokeret gives  5$ Gift Card to top 10 players Every two weeks. The End of First Round is 29 March 2020.":"Jokeret gives  5$ Gift Card to top 10 players Every two weeks. The End of First Round is 24 March 2020.",
      "No.":"No.",     
      "Kick the user":'Kick the user',      
      "Gifts received":"Gifts received",
      "Gifts sent":"Gifts sent",
      "Win":"Win",
      "Left":"Left",
      "Gifts":"Gifts",
      "Standard":"Standard",
      "Game":"Game",
      "Invite your friends.":"Invite your friends.",
      "Hello":"Hello",
      "Please play faster":"Please play faster",
      "Good Game":"Good Game",
      "Details: your partner must confirm cheat is happen and if you are wrong, your team loose this hand. and if you are right, your team wins this hand.":"Details: your partner must confirm cheat is happen and if you are wrong, your team loose this hand. and if you are right, your team wins this hand.",
      "Tap here to invite your friends from Telegram.":"Tap here to invite your friends from Telegram.",
      "Tap here to invite your friends from WhatsApp.":"Tap here to invite your friends from WhatsApp.",
      "Tap here to invite your friends from Facebook.":"Tap here to invite your friends from Facebook.",
      "Tap here to invite your friends from twitter.":"Tap here to invite your friends from twitter.",
      "Tab here to invite your friends from email.":"Tab here to invite your friends from email.",
      "Top players with more coins will earn Gift Cards tap here.":"Top players with more coins will earn Gift Cards tap here.",
      "To learn how to play tap here.":"To learn how to play tap here.",
      "To be familiar with how to earn coin tap here.":"To be familiar with how to earn coin tap here.",
      "Welcome, You receive 1000":"Welcome, You receive 1000",
      "Image Profile": "تصویر نمایه",
  

      
      
   }
])

